.TH "wetter" 1 "Tue Nov 13 2018" "wetter 1.0.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wetter -- command line weather report
.PP
.SS "SYNOPSIS"
.PP
.nf
\fBwetter\fP [LOCATION]
.fi
.PP
.SS "DESCRIPTION"
.I wetter
is a command line tool to get weather reports\&. It is a wrapper for the wttr.in website\&.
.SH OPTIONS
.B wetter
takes an option for the location. Without any option it gets the weather for your current location.
.SH EXAMPLES
.TP
Examples for getting a weather report.
.LP
.B wetter
gets the weather for your current locaton
.TP
.BI \fBwetter\fP \ frankfurt
gets the weather for Frankfurt
.SH BUGS
No known bugs.
.SH AUTHOR
Marco Schirrmeister (marco@marco.cx)